//! Persistent record of every conversation orcim has spawned, plus the
//! user-managed project display order (PLAN.md D5).

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Conversation {
    /// The Claude Code session id (uuid), generated by orcim at spawn time.
    pub id: String,
    /// Absolute working directory the conversation runs in.
    pub cwd: PathBuf,
    /// tmux pane id (`%42`) when live; `None` when Dead.
    pub pane_id: Option<String>,
    /// Unix seconds the user last had this conversation in the content pane.
    pub last_viewed: u64,
    /// Unix seconds the conversation was spawned.
    pub created_at: u64,
}

#[derive(Debug, Default, Serialize, Deserialize)]
pub struct State {
    /// Display order of project groups; append-only unless reordered by the
    /// user (Move mode).
    #[serde(default)]
    pub projects: Vec<String>,
    #[serde(default)]
    pub conversations: Vec<Conversation>,
}

impl State {
    pub fn load() -> Result<Self> {
        let path = state_file()?;
        match fs::read_to_string(&path) {
            Ok(text) => serde_json::from_str(&text)
                .with_context(|| format!("corrupt state file {}", path.display())),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Self::default()),
            Err(e) => Err(e).with_context(|| format!("reading {}", path.display())),
        }
    }

    /// Atomic write: temp file in the same directory, then rename over.
    pub fn save(&self) -> Result<()> {
        let path = state_file()?;
        let dir = path.parent().context("state file has no parent dir")?;
        fs::create_dir_all(dir)?;
        let tmp = dir.join("state.json.tmp");
        let text = serde_json::to_string_pretty(self)?;
        fs::write(&tmp, text).with_context(|| format!("writing {}", tmp.display()))?;
        fs::rename(&tmp, &path)
            .with_context(|| format!("renaming into place {}", path.display()))?;
        Ok(())
    }

    pub fn conversation(&self, id: &str) -> Option<&Conversation> {
        self.conversations.iter().find(|c| c.id == id)
    }

    pub fn conversation_mut(&mut self, id: &str) -> Option<&mut Conversation> {
        self.conversations.iter_mut().find(|c| c.id == id)
    }

    /// Record a freshly spawned conversation, appending its project to the
    /// order list if this is the project's first conversation (D9).
    pub fn add_conversation(&mut self, id: String, cwd: PathBuf, pane_id: String) {
        let project = cwd.display().to_string();
        if !self.projects.contains(&project) {
            self.projects.push(project);
        }
        let now = unix_now();
        self.conversations.push(Conversation {
            id,
            cwd,
            pane_id: Some(pane_id),
            last_viewed: now,
            created_at: now,
        });
    }
}

pub fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Generate a random v4 uuid (lowercase, hyphenated) for `--session-id`.
pub fn new_uuid() -> Result<String> {
    let mut bytes = [0u8; 16];
    fs::File::open("/dev/urandom")
        .context("opening /dev/urandom")?
        .read_exact(&mut bytes)?;
    bytes[6] = (bytes[6] & 0x0f) | 0x40; // version 4
    bytes[8] = (bytes[8] & 0x3f) | 0x80; // variant 10
    let h = |range: std::ops::Range<usize>| -> String {
        bytes[range].iter().map(|b| format!("{b:02x}")).collect()
    };
    Ok(format!(
        "{}-{}-{}-{}-{}",
        h(0..4),
        h(4..6),
        h(6..8),
        h(8..10),
        h(10..16)
    ))
}

fn state_file() -> Result<PathBuf> {
    let base = match std::env::var("XDG_STATE_HOME") {
        Ok(dir) if !dir.is_empty() => PathBuf::from(dir),
        _ => {
            let home = std::env::var("HOME").context("HOME not set")?;
            Path::new(&home).join(".local/state")
        }
    };
    Ok(base.join("orcim/state.json"))
}
