//! Persistent record of every conversation corc has spawned, plus the
//! user-managed project display order (PLAN.md D5).

use crate::ui::HistoryWindow;
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Conversation {
    /// The agent session id, generated by corc (Claude) or minted by the
    /// agent (Cursor `create-chat`) at spawn time.
    pub id: String,
    /// Absolute working directory the conversation runs in.
    pub cwd: PathBuf,
    /// tmux pane id (`%42`) when live; `None` when Dead.
    pub pane_id: Option<String>,
    /// Unix seconds the user last had this conversation in the content pane.
    pub last_viewed: u64,
    /// Unix seconds the conversation was spawned.
    pub created_at: u64,
    /// Which agent CLI spawned it — resume must use the same one. Absent in
    /// state files predating multi-provider support, defaulting to Claude.
    #[serde(default = "default_provider")]
    pub provider: String,
    /// Start of an in-flight turn, persisted so provider metadata can recover
    /// its elapsed time after corc restarts. Cleared when the turn completes.
    #[serde(default)]
    pub turn_started_at: Option<u64>,
    /// User-controlled placement in the always-visible top panel. Defaults to
    /// false so state files written before pinning support remain compatible.
    #[serde(default)]
    pub pinned: bool,
    /// Whether the browser view (D24) opens beside this conversation while it
    /// is the one in view. Per-conversation rather than one global pane, and
    /// persisted so the choice survives a corc restart.
    #[serde(default)]
    pub browser: bool,
    /// Profile key stays fixed when a provisional agent id becomes a real id.
    /// Older records use their session id until it first changes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub browser_profile: Option<String>,
    /// Unix seconds corc typed Claude's `/cd` for this conversation
    /// (ADR-0003). `cwd` is already the target, optimistically: Claude runs
    /// the queued `/cd` only when its turn ends. Cleared once Claude's own
    /// report settles it — see `settled_cwd`. Cursor moves are bookkeeping
    /// only and never enter this pending state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub relocation_requested_at: Option<u64>,
}

impl Conversation {
    pub fn browser_profile(&self) -> &str {
        self.browser_profile.as_deref().unwrap_or(&self.id)
    }

    pub fn resolve_id(&mut self, id: String) {
        if self.browser_profile.is_none() {
            self.browser_profile = Some(self.id.clone());
        }
        self.id = id;
    }

    /// Where the agent's report says this row belongs, when it says anything
    /// new. `meta.cwd` is the reported directory; with no relocation pending
    /// any change is a move (a `/cd` typed by hand).
    ///
    /// While one is pending the row already sits at the target, and the
    /// report counts only once it can be about the `/cd`: either it names the
    /// target (the move happened, whichever source noticed first), or a turn
    /// has started since the request — the queued `/cd` ran, or failed,
    /// before that prompt — and the report is the answer either way. Anything
    /// dated earlier is the directory the agent was in before the request,
    /// including the `Stop` of the very turn that made it.
    pub fn settled_cwd(&self, meta: &crate::discovery::Meta) -> Option<PathBuf> {
        let reported = meta.cwd.clone()?;
        let settled = match self.relocation_requested_at {
            None => reported != self.cwd,
            Some(since) => reported == self.cwd || meta.turn_started_at > Some(since),
        };
        settled.then_some(reported)
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub struct State {
    /// Display order of project groups; append-only unless reordered by the
    /// user (Move mode).
    #[serde(default)]
    pub projects: Vec<String>,
    #[serde(default)]
    pub conversations: Vec<Conversation>,
    /// Provider used for conversations spawned from now on; changed by the
    /// switch picker and persisted so the choice survives restarts.
    #[serde(default = "default_provider")]
    pub active_provider: String,
    /// Machine-local project directories, added on the fly through the `p`
    /// overlay (D20). Merged with the hand-curated, dotfile-synced list in
    /// `~/.config/corc/directories.txt`; this half is never synced.
    #[serde(default)]
    pub directories: Vec<String>,
    /// How far back the sidebar shows Dead conversations, cycled with `a`
    /// (D12) and persisted so the choice survives a restart.
    #[serde(default)]
    pub history_window: HistoryWindow,
}

fn default_provider() -> String {
    crate::provider::DEFAULT_ID.to_string()
}

impl Default for State {
    fn default() -> Self {
        Self {
            projects: Vec::new(),
            conversations: Vec::new(),
            active_provider: default_provider(),
            directories: Vec::new(),
            history_window: HistoryWindow::default(),
        }
    }
}

impl State {
    pub fn load() -> Result<Self> {
        let path = state_file()?;
        match fs::read_to_string(&path) {
            Ok(text) => {
                let mut state: Self = serde_json::from_str(&text)
                    .with_context(|| format!("corrupt state file {}", path.display()))?;
                // Drop projects whose conversations have all gone away: they are
                // invisible in the list but still occupy a slot in the move-mode
                // order, which makes reordering skip "dead" steps (D9).
                state.prune_empty_projects();
                Ok(state)
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Self::default()),
            Err(e) => Err(e).with_context(|| format!("reading {}", path.display())),
        }
    }

    /// Remove any project from the display order that no longer has a
    /// conversation. `state.projects` is otherwise only ever appended to
    /// (`add_conversation`), so without this an emptied project lingers as an
    /// invisible row that reorder still steps across. Returns whether anything
    /// was removed.
    pub fn prune_empty_projects(&mut self) -> bool {
        let live: std::collections::HashSet<String> = self
            .conversations
            .iter()
            .map(|c| c.cwd.display().to_string())
            .collect();
        let before = self.projects.len();
        self.projects.retain(|project| live.contains(project));
        self.projects.len() != before
    }

    /// Atomic write: temp file in the same directory, then rename over.
    ///
    /// Before writing, fold in any machine-local `directories` a second writer
    /// (the `corc projects` sessionizer, D22) appended since we loaded. The TUI
    /// holds state in memory, so without this its next save would clobber that
    /// addition. `directories` is append-only — there is no removal — so the
    /// union is lossless and makes the field safe for both writers.
    pub fn save(&mut self) -> Result<()> {
        let path = state_file()?;
        self.merge_disk_directories(&path);
        let dir = path.parent().context("state file has no parent dir")?;
        fs::create_dir_all(dir)?;
        let tmp = dir.join("state.json.tmp");
        let text = serde_json::to_string_pretty(self)?;
        fs::write(&tmp, text).with_context(|| format!("writing {}", tmp.display()))?;
        fs::rename(&tmp, &path)
            .with_context(|| format!("renaming into place {}", path.display()))?;
        Ok(())
    }

    /// Union the on-disk machine-local `directories` into ours, preserving
    /// order and appending only entries we don't already have. Best-effort: a
    /// missing or unparsable file just leaves our list untouched.
    fn merge_disk_directories(&mut self, path: &Path) {
        #[derive(Deserialize)]
        struct DiskDirs {
            #[serde(default)]
            directories: Vec<String>,
        }
        let Ok(text) = fs::read_to_string(path) else {
            return;
        };
        let Ok(disk) = serde_json::from_str::<DiskDirs>(&text) else {
            return;
        };
        for entry in disk.directories {
            if !self.directories.contains(&entry) {
                self.directories.push(entry);
            }
        }
    }

    /// Append a machine-local project directory unless it is already listed
    /// (D20). Returns whether it was newly added. The hand-curated
    /// `directories.txt` is never touched — that file is edited by hand.
    pub fn add_directory(&mut self, dir: &Path) -> bool {
        let entry = dir.to_string_lossy().to_string();
        if self.directories.iter().any(|d| d == &entry) {
            return false;
        }
        self.directories.push(entry);
        true
    }

    pub fn conversation(&self, id: &str) -> Option<&Conversation> {
        self.conversations.iter().find(|c| c.id == id)
    }

    pub fn conversation_mut(&mut self, id: &str) -> Option<&mut Conversation> {
        self.conversations.iter_mut().find(|c| c.id == id)
    }

    /// Transfer a pane after its CLI switched sessions. Existing destination
    /// preferences survive; the previous session remains resumable in history.
    pub fn resume_in_pane(
        &mut self,
        pane: &str,
        session: &crate::resume::Session,
    ) -> Option<String> {
        let source = self
            .conversations
            .iter()
            .position(|c| c.pane_id.as_deref() == Some(pane) && c.provider == session.provider)?;
        let old = self.conversations[source].clone();
        if old.id == session.id {
            return None;
        }
        if self
            .conversation(&session.id)
            .is_some_and(|c| c.provider != session.provider)
        {
            return None;
        }
        self.conversations[source].pane_id = None;
        let pending = crate::provider::by_id(&old.provider).is_pending(&old.id);
        if self.conversation(&session.id).is_none() {
            if pending {
                self.conversations[source].resolve_id(session.id.clone());
                self.conversations[source].pane_id = Some(pane.into());
            } else {
                self.add_conversation(
                    session.id.clone(),
                    old.cwd.clone(),
                    pane.into(),
                    session.provider.clone(),
                );
            }
        } else {
            let target = self.conversation_mut(&session.id).unwrap();
            target.pane_id = Some(pane.into());
            target.last_viewed = unix_now();
            target.relocation_requested_at = None;
        }
        if pending {
            self.conversations.retain(|c| c.id != old.id);
        }
        Some(old.id)
    }

    /// Record a freshly spawned conversation, appending its project to the
    /// order list if this is the project's first conversation (D9).
    pub fn add_conversation(
        &mut self,
        id: String,
        cwd: PathBuf,
        pane_id: String,
        provider: String,
    ) {
        let project = cwd.display().to_string();
        if !self.projects.contains(&project) {
            self.projects.push(project);
        }
        let now = unix_now();
        self.conversations.push(Conversation {
            id,
            cwd,
            pane_id: Some(pane_id),
            last_viewed: now,
            created_at: now,
            provider,
            turn_started_at: None,
            pinned: false,
            browser: false,
            browser_profile: None,
            relocation_requested_at: None,
        });
    }

    /// Re-home a conversation: directly for a bookkeeping-only Cursor move,
    /// or on Claude's own word after `/cd` (ADR-0003). Appends a new project
    /// to the display order, drops an empty old project, and settles any
    /// pending relocation. Returns whether anything changed.
    pub fn relocate(&mut self, id: &str, cwd: &Path) -> bool {
        let Some(conv) = self.conversation_mut(id) else {
            return false;
        };
        let settled = conv.relocation_requested_at.take().is_some();
        if conv.cwd == cwd {
            return settled;
        }
        conv.cwd = cwd.to_path_buf();
        let project = cwd.display().to_string();
        if !self.projects.contains(&project) {
            self.projects.push(project);
        }
        self.prune_empty_projects();
        true
    }

    /// The optimistic half of Claude's `corc cd` (ADR-0003): corc has just
    /// typed `/cd` into the pane, so move the row now and remember that Claude
    /// has yet to confirm it. `relocate` settles it later, either way.
    pub fn request_relocation(&mut self, id: &str, cwd: &Path, now: u64) -> bool {
        self.relocate(id, cwd);
        let Some(conv) = self.conversation_mut(id) else {
            return false;
        };
        conv.relocation_requested_at = Some(now);
        true
    }

    /// Toggle a conversation's persisted pin and return its new state.
    pub fn toggle_pin(&mut self, id: &str) -> Option<bool> {
        let conversation = self.conversation_mut(id)?;
        conversation.pinned = !conversation.pinned;
        Some(conversation.pinned)
    }
}

pub fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Generate a random v4 uuid (lowercase, hyphenated) for `--session-id`.
pub fn new_uuid() -> Result<String> {
    let mut bytes = [0u8; 16];
    fs::File::open("/dev/urandom")
        .context("opening /dev/urandom")?
        .read_exact(&mut bytes)?;
    bytes[6] = (bytes[6] & 0x0f) | 0x40; // version 4
    bytes[8] = (bytes[8] & 0x3f) | 0x80; // variant 10
    let h = |range: std::ops::Range<usize>| -> String {
        bytes[range].iter().map(|b| format!("{b:02x}")).collect()
    };
    Ok(format!(
        "{}-{}-{}-{}-{}",
        h(0..4),
        h(4..6),
        h(6..8),
        h(8..10),
        h(10..16)
    ))
}

/// Where corc keeps everything machine-local: `state.json` and the provider
/// metadata caches beside it.
pub fn state_dir() -> Result<PathBuf> {
    let base = match std::env::var("XDG_STATE_HOME") {
        Ok(dir) if !dir.is_empty() => PathBuf::from(dir),
        _ => {
            let home = std::env::var("HOME").context("HOME not set")?;
            Path::new(&home).join(".local/state")
        }
    };
    Ok(base.join("corc"))
}

pub fn state_file() -> Result<PathBuf> {
    Ok(state_dir()?.join("state.json"))
}

/// Write a generated file only when its content has drifted, atomically. For
/// the files corc hands to an agent on its spawn line: regenerated from the
/// current binary and environment on every use, so they follow a moved
/// install without anyone remembering to refresh them.
pub fn write_if_changed(path: &Path, wanted: &str) -> Result<()> {
    if std::fs::read_to_string(path).ok().as_deref() == Some(wanted) {
        return Ok(());
    }
    let dir = path.parent().context("path has no parent")?;
    std::fs::create_dir_all(dir)?;
    let tmp = dir.join(format!(
        "{}.tmp",
        path.file_name().and_then(|n| n.to_str()).unwrap_or("file")
    ));
    std::fs::write(&tmp, wanted)?;
    std::fs::rename(&tmp, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{Conversation, HistoryWindow, State};

    #[test]
    fn old_conversation_state_defaults_new_persisted_metadata() {
        let conversation: Conversation = serde_json::from_str(
            r#"{
                "id":"chat",
                "cwd":"/tmp",
                "pane_id":null,
                "last_viewed":1,
                "created_at":1,
                "provider":"cursor"
            }"#,
        )
        .unwrap();
        assert_eq!(conversation.turn_started_at, None);
        assert!(!conversation.pinned);
        assert!(!conversation.browser);
    }

    /// ADR-0003: relocation re-homes the row and keeps the project list in
    /// step — the new project appears, the old one survives while a sibling
    /// conversation still lives there and is pruned with the last one.
    #[test]
    fn relocation_rehomes_conversation_and_project_list() {
        let mut state = State::default();
        for id in ["a", "b"] {
            state.conversations.push(Conversation {
                id: id.into(),
                cwd: "/work/old".into(),
                pane_id: None,
                last_viewed: 1,
                created_at: 1,
                provider: "claude".into(),
                turn_started_at: None,
                pinned: false,
                browser: false,
                browser_profile: None,
                relocation_requested_at: None,
            });
        }
        state.projects.push("/work/old".into());

        use std::path::Path;
        assert!(state.relocate("a", Path::new("/work/new")));
        assert_eq!(state.conversation("a").unwrap().cwd, Path::new("/work/new"));
        assert_eq!(state.projects, vec!["/work/old", "/work/new"]);

        // Same cwd again is a no-op; an unknown id changes nothing.
        assert!(!state.relocate("a", Path::new("/work/new")));
        assert!(!state.relocate("missing", Path::new("/anywhere")));

        // The last conversation leaving prunes the old project.
        assert!(state.relocate("b", Path::new("/work/new")));
        assert_eq!(state.projects, vec!["/work/new"]);
    }

    /// `corc cd` moves the row the moment `/cd` is typed, and the agent's
    /// report settles it: a report naming the target confirms whenever it
    /// arrives; a report from before the request is the old directory and
    /// says nothing; a turn that started after the request means the queued
    /// `/cd` has had its chance, so whatever the report says then is final.
    #[test]
    fn a_requested_relocation_is_optimistic_until_the_agent_reports() {
        use crate::discovery::Meta;
        use std::path::Path;
        let mut state = State::default();
        state.add_conversation("a".into(), "/work/old".into(), "%1".into(), "claude".into());
        let meta = |cwd: &str, turn_started_at: Option<u64>| Meta {
            cwd: Some(cwd.into()),
            turn_started_at,
            ..Meta::default()
        };

        assert!(state.request_relocation("a", Path::new("/work/new"), 1000));
        let conv = state.conversation("a").unwrap();
        assert_eq!(conv.cwd, Path::new("/work/new"));
        assert_eq!(state.projects, vec!["/work/new"]);

        // The hook log still ends on the old directory, from before the
        // request: not evidence.
        assert_eq!(conv.settled_cwd(&meta("/work/old", Some(900))), None);
        // The transcript's `relocated` record carries no time and needs none.
        assert_eq!(
            conv.settled_cwd(&meta("/work/new", Some(900))),
            Some("/work/new".into())
        );
        // A prompt after the request, still in the old directory: `/cd` was
        // refused or never ran, and the row goes back.
        assert_eq!(
            conv.settled_cwd(&meta("/work/old", Some(1100))),
            Some("/work/old".into())
        );

        assert!(state.relocate("a", Path::new("/work/old")));
        let conv = state.conversation("a").unwrap();
        assert_eq!(conv.cwd, Path::new("/work/old"));
        assert_eq!(conv.relocation_requested_at, None);
        // Settled: only a real change counts again.
        assert_eq!(conv.settled_cwd(&meta("/work/old", Some(1100))), None);
        assert_eq!(
            conv.settled_cwd(&meta("/work/else", Some(1100))),
            Some("/work/else".into())
        );
    }

    /// The `a` history window is a setting, not session state: it survives a
    /// restart, and a state file written before it existed still loads.
    #[test]
    fn history_window_round_trips_and_defaults_on_older_state_files() {
        let mut state = State::default();
        assert_eq!(state.history_window, HistoryWindow::OneWeek);

        state.history_window = HistoryWindow::ThreeHours;
        let json = serde_json::to_string(&state).unwrap();
        let restored: State = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.history_window, HistoryWindow::ThreeHours);

        let older: State = serde_json::from_str(r#"{"conversations":[]}"#).unwrap();
        assert_eq!(older.history_window, HistoryWindow::OneWeek);
    }

    #[test]
    fn pin_toggle_is_persisted_on_the_conversation() {
        let mut state = State::default();
        state.conversations.push(Conversation {
            id: "chat".into(),
            cwd: "/tmp".into(),
            pane_id: None,
            last_viewed: 1,
            created_at: 1,
            provider: "claude".into(),
            turn_started_at: None,
            pinned: false,
            browser: false,
            browser_profile: None,
            relocation_requested_at: None,
        });

        assert_eq!(state.toggle_pin("chat"), Some(true));
        assert!(state.conversation("chat").unwrap().pinned);
        let json = serde_json::to_string(&state).unwrap();
        let mut restored: State = serde_json::from_str(&json).unwrap();
        assert!(restored.conversation("chat").unwrap().pinned);
        assert_eq!(restored.toggle_pin("chat"), Some(false));
        assert_eq!(restored.toggle_pin("missing"), None);
    }
}
